import pandas as pd
import numpy as np
import ta
from ta.trend import EMAIndicator, MACD
from ta.momentum import RSIIndicator
from ta.volatility import AverageTrueRange
from ta.volume import VolumeWeightedAveragePrice

class FeatureEngineer:
    def __init__(self, config=None):
        self.config = config

    def add_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Adds technical indicators to the DataFrame.
        Includes 4h context features by resampling.
        """
        if df.empty:
            return df
        
        df = df.copy()
        df["timestamp"] = pd.to_datetime(df["timestamp"])
        df = df.sort_values("timestamp").reset_index(drop=True)

        # 1. 1h Indicators (Standard)
        df["RSI"] = RSIIndicator(close=df["close"], window=14).rsi()
        macd = MACD(close=df["close"])
        df["MACD"] = macd.macd()
        df["MACD_Signal"] = macd.macd_signal()
        df["MACD_Diff"] = macd.macd_diff()
        df["EMA_9"] = EMAIndicator(close=df["close"], window=9).ema_indicator()
        df["EMA_20"] = EMAIndicator(close=df["close"], window=20).ema_indicator()
        df["EMA_50"] = EMAIndicator(close=df["close"], window=50).ema_indicator()
        df["ATR"] = AverageTrueRange(high=df["high"], low=df["low"], close=df["close"], window=14).average_true_range()
        df["VWAP"] = VolumeWeightedAveragePrice(
            high=df["high"], low=df["low"], close=df["close"], volume=df["volume"], window=14
        ).volume_weighted_average_price()
        df["Volume_Delta"] = np.where(df["close"] > df["open"], df["volume"], -df["volume"])

        # 2. 4h Context Indicators
        # Resample to 4h
        df_tmp = df.set_index("timestamp")
        df_4h = df_tmp.resample('4H').agg({
            'open': 'first',
            'high': 'max',
            'low': 'min',
            'close': 'last',
            'volume': 'sum'
        }).dropna()

        df_4h["RSI_4h"] = RSIIndicator(close=df_4h["close"], window=14).rsi()
        macd_4h = MACD(close=df_4h["close"])
        df_4h["MACD_4h"] = macd_4h.macd()
        df_4h["ATR_4h"] = AverageTrueRange(high=df_4h["high"], low=df_4h["low"], close=df_4h["close"], window=14).average_true_range()

        # Join back to 1h using merge_asof (matches 1h bar to the latest available 4h bar)
        df_4h = df_4h.reset_index()
        df_4h = df_4h.sort_values("timestamp")
        
        df = pd.merge_asof(
            df, 
            df_4h[["timestamp", "RSI_4h", "MACD_4h", "ATR_4h"]], 
            on="timestamp", 
            direction="backward"
        )
        
        # 3. Time Features
        df["Hour"] = df["timestamp"].dt.hour
        df["DayOfWeek"] = df["timestamp"].dt.dayofweek

        return df

    def create_target(self, df: pd.DataFrame, horizon_minutes: int = 30, threshold: float = 0.002) -> pd.DataFrame:
        """
        Creates target variable for ML:
        1 (Buy/Up) if price increases > threshold in 'horizon_minutes'
        0 (Hold/Down) otherwise
        
        Note: DataFrame index must be DatetimeIndex or 'timestamp' column used for lookahead.
        Since our data is aggregated (e.g., 1h bars), 'horizon_minutes' implies 'next n bars'.
        If timeframe is 1h, horizon 60m = 1 bar.
        """
        df = df.copy()
        
        # Calculate Future Return
        # Shift(-1) implies looking at the NEXT bar's close vs Current Close.
        # Ideally we want (Future Close - Current Close) / Current Close
        
        # Determine number of periods to shift based on data frequency
        # Simplification: assume 1 period shift represents the horizon if matched
        shift_period = 1 
        
        df["Future_Close"] = df["close"].shift(-shift_period)
        df["Target_Return"] = (df["Future_Close"] - df["close"]) / df["close"]
        
        # Binary Target
        # 1 if returns > threshold, 0 otherwise (can be expanded to -1 for puts)
        df["Target"] = (df["Target_Return"] > threshold).astype(int)
        
        # Drop NaN values generated by shifting
        df.dropna(subset=["Future_Close"], inplace=True)
        
        return df

if __name__ == "__main__":
    # Test
    # Load a sample file
    import os
    data_dir = "data"
    files = [f for f in os.listdir(data_dir) if f.endswith(".csv")]
    if files:
        df = pd.read_csv(os.path.join(data_dir, files[0]))
        df["timestamp"] = pd.to_datetime(df["timestamp"])
        
        fe = FeatureEngineer()
        df = fe.add_indicators(df)
        df = fe.create_target(df)
        
        print("Features added:", df.columns.tolist())
        print(df[["timestamp", "close", "RSI", "Target"]].tail())
